### ISSUE TITLE
Aggiungere log

### ISSUE THREAD

**Issue by edomora97** [TheEntropics/TeamSpeak3-stats#3]
Implementare un log dettagliato dell'applicazione.

Dovranno essere presenti:
- Tempo totale di esecuzione
- Tempo di ogni analisi
- Tempo di parsing delle righe
- Numero di righe nuove

**Comment by MarcoCivettini** [comment]
La smetti?
Il 17/nov/2015 19:44, "Edoardo Morassutto" notifications@github.com ha
scritto:

**Comment by edomora97** [comment]
Ahahahaha
